// preload.js

const { contextBridge, ipcRenderer } = require('electron');


contextBridge.exposeInMainWorld('electronAPI', {
  selectScreenshotFolder: () => ipcRenderer.invoke('select-screenshot-folder'),
  getScreenshotFolder: (videoPath) => ipcRenderer.invoke('get-screenshot-folder', videoPath),
  openVideoDialog: () => ipcRenderer.send('open-video-dialog'),
  onVideoSelected: (callback) => ipcRenderer.on('video-selected', (event, path) => callback(path)),
  saveScreenshot: (filePath, buffer) => ipcRenderer.invoke('save-screenshot', { filePath, buffer }),
  addMediaItem: (item) => ipcRenderer.invoke('add-media-item', item),
  getOrCreateMediaItem: (filePath) => ipcRenderer.invoke('get-or-create-media-item', filePath),
  getMediaItemByFilePath: (filePath) => ipcRenderer.invoke('get-media-item-by-file-path', filePath),
  insertScreenshot: (payload) => ipcRenderer.invoke('insert-screenshot', payload),
  getMediaItems: () => ipcRenderer.invoke('get-media-items'),
  getScreenshotsForMediaItem: (mediaItemId, limit) => ipcRenderer.invoke('get-screenshots-for-media-item', mediaItemId, limit),
  getExportedVideosForMediaItem: (mediaItemId) => ipcRenderer.invoke('get-exported-videos-for-media-item', mediaItemId),
  getRandomUnseenScreenshots: (limit) => ipcRenderer.invoke('get-random-unseen-screenshots', limit),
  startRandomScreenshotStream: (payload) => ipcRenderer.send('start-random-screenshot-stream', payload),
  cancelRandomScreenshotStream: (requestId) => ipcRenderer.send('cancel-random-screenshot-stream', requestId),
  onRandomScreenshotStreamItem: (callback) => ipcRenderer.on('random-screenshot-stream-item', (event, data) => callback(data)),
  onRandomScreenshotStreamComplete: (callback) => ipcRenderer.on('random-screenshot-stream-complete', (event, data) => callback(data)),
  onRandomScreenshotStreamError: (callback) => ipcRenderer.on('random-screenshot-stream-error', (event, data) => callback(data)),
  getIgnoredScreenshots: () => ipcRenderer.invoke('get-ignored-screenshots'),
  migrateScreenshotsFromFolder: () => ipcRenderer.invoke('migrate-screenshots-from-folder'),
  markScreenshotDisplayed: (screenshotIds) => ipcRenderer.invoke('mark-screenshot-displayed', screenshotIds),
  ignoreScreenshot: (screenshotId, ignored = 1) => ipcRenderer.invoke('ignore-screenshot', screenshotId, ignored),
  getMediaItemForScreenshot: (screenshotId) => ipcRenderer.invoke('get-media-item-for-screenshot', screenshotId),
  readScreenshots: (folder, name, imageCount) => ipcRenderer.invoke('read-screenshots', folder, name, imageCount),
  showContextMenu: (payload) => ipcRenderer.send('show-context-menu', payload),
  onContextCommand: (callback) => ipcRenderer.on('context-menu-command', (event, data) => callback(data)),
  onOpenMediaTable: (callback) => ipcRenderer.on('open-media-table', callback),
  deleteMediaItem: (id) => ipcRenderer.invoke('delete-media-item', id),
  openSettingsWindow: () => ipcRenderer.send('open-settings-window'),
  setVideoPlayerVisibility: (isVisible) => ipcRenderer.send('set-video-player-visibility', isVisible),
  onVideoPlayerVisibilityChanged: (callback) => ipcRenderer.on('video-player-visibility-changed', (event, isVisible) => callback(isVisible)),
  exportVideoRange: (payload) => ipcRenderer.invoke('export-video-range', payload),
  openMediaTable: () => ipcRenderer.send('open-media-table'),
   getAppSettings: () => ipcRenderer.invoke('get-app-settings'),
  updateAppSetting: (key, value) => ipcRenderer.send('update-app-setting', { key, value }),
  getDatabasePath: () => ipcRenderer.invoke('get-database-path'),
  selectExistingDatabaseFile: () => ipcRenderer.invoke('select-existing-database-file'),
  createDatabaseFile: () => ipcRenderer.invoke('create-database-file'),
  openScreenshotFolder: (filePath) => ipcRenderer.send('open-screenshot-folder', filePath),
  openFileLocation: (filePath) => ipcRenderer.send('open-file-location', filePath),
  searchMediaItems: (query) => ipcRenderer.invoke('search-media-items', query),
  getMediaItemByName: (name) => ipcRenderer.invoke('get-media-item-by-name', name),
  getMediaItemById: (mediaItemId) => ipcRenderer.invoke('get-media-item-by-id', mediaItemId),
  updateMediaItemImageList: (payload) => ipcRenderer.invoke('update-media-item-image-list', payload),
  deleteUnselectedScreenshotsForMediaItem: (payload) => ipcRenderer.invoke('delete-unselected-screenshots-for-media-item', payload),
  getAllMediaItems: () => ipcRenderer.invoke('get-all-media-items'),
  getMediaLists: () => ipcRenderer.invoke('get-media-lists'),
  createMediaList: (name) => ipcRenderer.invoke('create-media-list', name),
  deleteMediaList: (listId) => ipcRenderer.invoke('delete-media-list', listId),
  addMediaItemToList: (payload) => ipcRenderer.invoke('add-media-item-to-list', payload),
  removeMediaItemFromList: (payload) => ipcRenderer.invoke('remove-media-item-from-list', payload),
  getMediaItemsForList: (listId) => ipcRenderer.invoke('get-media-items-for-list', listId),
  getDisplayedScreenshotPaths: () => ipcRenderer.invoke('get-displayed-screenshot-paths'),
  markDisplayedScreenshots: (paths) => ipcRenderer.invoke('mark-displayed-screenshots', paths),
  clearDisplayedScreenshots: () => ipcRenderer.invoke('clear-displayed-screenshots'),
  getIgnoredRandomScreenshotPaths: () => ipcRenderer.invoke('get-ignored-random-screenshot-paths'),
  ignoreRandomScreenshot: (path) => ipcRenderer.invoke('ignore-random-screenshot', path),

});
